# Generated by Django 4.2.30 on 2026-05-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="tables.table"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "menu_item"), name="unique_order_item"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["table", "status"], name="rms_orders_table_i_1b8ddf_idx"),
        ),
    ]
