# Generated by Django 4.2.30 on 2026-05-27 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="station",
            field=models.CharField(choices=[("kitchen", "Kitchen"), ("bar", "Bar")], default="kitchen", max_length=10),
        ),
        migrations.CreateModel(
            name="OrderStationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("station", models.CharField(choices=[("kitchen", "Kitchen"), ("bar", "Bar")], max_length=10)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("items_snapshot", models.JSONField(default=list)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="station_logs", to="orders.order"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="station_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rms_order_station_logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
