# Generated by Django 4.2.30 on 2026-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_notes_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="unit_mrp",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
