# Generated by Django 4.2.30 on 2026-05-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "rms_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="menu/images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="items", to="menu.category"
                    ),
                ),
            ],
            options={
                "db_table": "rms_menu_items",
                "indexes": [
                    models.Index(fields=["category", "is_available"], name="rms_menu_it_categor_b63319_idx"),
                    models.Index(fields=["deleted_at"], name="rms_menu_it_deleted_fae694_idx"),
                ],
            },
        ),
    ]
