# Generated by Django 4.2.30 on 2026-05-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="station",
            field=models.CharField(choices=[("kitchen", "Kitchen"), ("bar", "Bar")], default="kitchen", max_length=10),
        ),
    ]
