# Generated by Django 4.2.30 on 2026-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_category_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum Retail Price (MRP). If blank, price is used.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
