# Generated by Django 4.2.30 on 2026-05-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tax_rate", models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ("restaurant_name", models.CharField(default="My Restaurant", max_length=200)),
                ("address", models.TextField(blank=True)),
                ("allow_staff_discount", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "rms_system_settings",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("none", "None"), ("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card"), ("wallet", "Digital Wallet")], max_length=20
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rms_bills",
            },
        ),
    ]
