# Generated by Django 4.2.30 on 2026-05-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="order",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="bill", to="orders.order"),
        ),
    ]
