# Generated by Django 4.2.30 on 2026-05-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
