# Generated by Django 4.2.30 on 2026-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_systemsettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Digital Wallet'), ('esewa', 'eSewa')], max_length=20),
        ),
    ]
