# Generated by Django 4.2.30 on 2026-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_bill_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="gross_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="nontaxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="vat_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive (tax added on top)"),
                    ("inclusive", "Inclusive (MRP – tax included in price)"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="vat_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive (tax added on top)"),
                    ("inclusive", "Inclusive (MRP – tax included in price)"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
    ]
