# Generated by Django 4.2.30 on 2026-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_bill_gross_amount_bill_net_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="customer_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bill",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="bill",
            name="customer_pan",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
