# Generated by Django 4.2.30 on 2026-05-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_bill_customer_address_bill_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="gross_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="net_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="nontaxable_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="taxable_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="vat_mode",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="vat_mode",
        ),
    ]
